name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: |
          docker login -u $DOCKER_PASS -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --tag smoketest-docker-webserver:$(date +%s)
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/smoketest-docker-webserver
