name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag smoketest-docker-webserver:$(date +%s)
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/smoketest-docker-webserver
